// <auto-generated />
using CP_MVC_RM550889.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CP_MVC_RM550889.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CP_MVC_RM550889.Models.Avaliacao", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Comentario")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("TituloDaAvaliacao")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<int>("UserAvaliacao")
                    .HasColumnType("NUMBER(10)");

                b.Property<int>("UserId")
                    .HasColumnType("NUMBER(10)");

                b.HasKey("Id");

                b.ToTable("PZ_Avaliacoes");
            });

            modelBuilder.Entity("CP_MVC_RM550889.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("UserEmail")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("UserPassword")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("UserPhone")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("Id");

                b.ToTable("PZ_Users");
            });
#pragma warning restore 612, 618
        }
    }
}

